on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: stats before clean
        run: |
          df -h
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -100
      - name: clean
        run: |
          sudo rm -rf /usr/local/*
          sudo apt purge dotnet* google-chrome-stable temurin* google-cloud-sdk hhvm azure-cli llvm* libllvm* gcc* mongodb* powershell firefox
      - name: test kas-container
        run: |
          wget https://raw.githubusercontent.com/siemens/kas/master/kas-container
          chmod a+x kas-container
          ./kas-container build --help
      - name: stats after clean
        run: |
          df -h
